In [4]:
import pandas as pd
import glob
import os
import numpy as np

def normalize(column):
    return (column - column.min()) / (column.max() - column.min())

In [5]:
path = os.getcwd()
df = pd.read_csv(path + "\data\Counties_Schools_Counts.csv")
display(df.head())

     County  Pub_Count  Non_Pup_Count  Uni_Count  Total
0  BEAUFORT         15              4          1     20
1     UNION         53             23          1     77
2      PITT         36             18          2     56
3     MOORE         25             13          1     39
4   HAYWOOD         16              5          1     22

In [7]:
df['Norm_Count'] = normalize(df['Total'])
display(df.head())

     County  Pub_Count  Non_Pup_Count  Uni_Count  Total  Norm_Count
0  BEAUFORT         15              4          1     20    0.058219
1     UNION         53             23          1     77    0.253425
2      PITT         36             18          2     56    0.181507
3     MOORE         25             13          1     39    0.123288
4   HAYWOOD         16              5          1     22    0.065068

In [10]:
df.to_csv(path + '\\data\\nc_schools_count.csv', index=False)